services:
  theentertainmentdatabase:
    build:
      context: .
    image: ghcr.io/raroh73/theentertainmentdatabase:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOSTNAME: postgres
      DB_USERNAME: username
      DB_PASSWORD: password
    ports:
      - "8080:8080"
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      retries: 5
      timeout: 5s
